# the EXISTING image i want  to start with i.e. the base image
# FROM node:14-alpine
# WORKDIR /app
FROM node:22-alpine
WORKDIR /app
COPY ./app.js ./
CMD node app.js

# docker build -t node-app .
# docker run -it node-app
